### ISSUE TITLE
Uses a centralised data approach.

### ISSUE THREAD

**Issue by nturpin0** [nhsx/COVID-19-app-iOS-BETA#21]
**Describe the bug**
Uses a centralised data approach.

**To Reproduce**
Use the app

**Expected behaviour**
Privacy 
**Smartphone (please complete the following information):**
Affects iOS and android.

**Additional context**
May affect chances of international travel.
https://uk.reuters.com/article/uk-health-coronavirus-europe-tech/european-coalition-takes-shape-on-coronavirus-contact-tracing-idUKKBN22J1LL

**Comment by edent** [comment]
You can read more about the approach at:

* https://www.ncsc.gov.uk/blog-post/security-behind-nhs-contact-tracing-app
* https://www.nhsx.nhs.uk/blogs/digital-contact-tracing-protecting-nhs-and-saving-lives/

We are in constant discussion with other countries about their approach. We realise that users will probably not want to download a separate app for every country they visit.

**Comment by HeadBoffin** [comment]
As this issue was all over the media, it's not much of an issue - and the benefits could be regarded to outweigh any perceived negatives and the majority of people aren't going to be off on international travel any time soon and the Apple/Google API is just that, not a solution, just something for others to implement AND isn't available for another week or more. But apart from that ...

**Comment by nturpin0** [comment]
Not _much_ of an issue is still an issue.

The benefits of decentralised could _also_ be regarded to outweigh any perceived negatives, and actual negatives of centralised. Wider adoption, works more reliably, works on more devices, less false triggering, Scotland may adopt, solves the whole island Ireland issue.
Shipping, trucking, air freight whilst not the majority of people undertaking international travel is still quite important. 
 
Apple API has been available to devs for a week, and sample code is available.

Looking at the approach its clear the team at nhsx aren't specifically looking to compromise peoples privacy with the app but there _are_ a issues with the approach, how its been presented and the data protection compliance. None of which is going to help build the trust that is needed to get everyone to use the app.

https://osf.io/preprints/lawarxiv/6fvgh

**Comment by christhomas** [comment]
There isn't a chance in hell I would ever install this after learning what you guys are up to. Have you lost your minds? You aren't exactly the best developers at the best of times and the NHS has a lousy track record of developing IT resources. 

I'm recommending nobody I know to install this and I'm spreading this far and wide as possible to anybody who will listen because I don't think anybody wants to install spyware on their phone, which this absolutely is. I'm advising to wait until the Apple/Google protocols become available.

You guys can empire build all you want, but the Apple/Google system is far superior than this will ever be.

**Comment by christhomas** [comment]
Considering alone the GDPR compliance in that I cannot have my data deleted on request and neither can I request a full copy of the data that you are storing about my device and my movements. But I guess you're going to hide behind Brexit when it comes to those issues right?

**Comment by christhomas** [comment]
"We realise that users will probably not want to download a separate app for every country they visit."

Exactly, I'll have an Apple/Google compatible software which will record the data in a single format, no matter what country I visit and it'll work globally because of it's decentralised nature.

Even more reason to never touch this privacy nightmare of an application with a hot barge pole

**Comment by edent** [comment]
Users are reminded of this repo's Code of Conduct. https://github.com/nhsx/COVID-19-app-iOS-BETA/blob/master/CODE_OF_CONDUCT.md
